In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2022-ukraine-russian-war/russia_losses_equipment.csv
/kaggle/input/2022-ukraine-russian-war/russia_losses_equipment_correction.csv
/kaggle/input/2022-ukraine-russian-war/russia_losses_personnel.csv

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('/kaggle/input/2022-ukraine-russian-war/russia_losses_equipment.csv')
df.head()

,date,day,aircraft,helicopter,tank,APC,field artillery,MRL,military auto,fuel tank,drone,naval ship,anti-aircraft warfare,special equipment,mobile SRBM system,greatest losses direction,vehicles and fuel tanks,cruise missiles,submarines
0,2024-09-22,942,369,328,8768,17222,18333,1195,NaN,NaN,15628,28,949,3144.0,NaN,NaN,25023.0,2593.0,1.0
1,2024-09-21,941,369,328,8746,17170,18270,1193,NaN,NaN,15561,28,949,3125.0,NaN,NaN,24966.0,2593.0,1.0
2,2024-09-20,940,369,328,8725,17132,18212,1189,NaN,NaN,15469,28,949,3115.0,NaN,NaN,24898.0,2593.0,1.0
3,2024-09-19,939,369,328,8705,17093,18177,1189,NaN,NaN,15417,28,947,3109.0,NaN,NaN,24839.0,2592.0,1.0
4,2024-09-18,938,369,328,8691,17080,18154,1188,NaN,NaN,15354,28,947,3109.0,NaN,NaN,24784.0,2592.0,1.0

In [4]:
# Convert date column to datetime format
df['date'] = pd.to_datetime(df['date'])

In [5]:
# Step 2: Data Overview
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941 entries, 0 to 940
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   date                       941 non-null    datetime64[ns]
 1   day                        941 non-null    int64
 2   aircraft                   941 non-null    int64
 3   helicopter                 941 non-null    int64
 4   tank                       941 non-null    int64
 5   APC                        941 non-null    int64
 6   field artillery            941 non-null    int64
 7   MRL                        941 non-null    int64
 8   military auto              65 non-null     float64
 9   fuel tank                  65 non-null     float64
 10  drone                      941 non-null    int64
 11  naval ship                 941 non-null    int64
 12  anti-aircraft warfare      941 non-null    int64
 13  special equipment          922 non-null    float64
 14  mobile SRBM system         36 non-null     float64
 15  greatest losses direction  203 non-null    object
 16  vehicles and fuel tanks    876 non-null    float64
 17  cruise missiles            876 non-null    float64
 18  submarines                 375 non-null    float64
dtypes: datetime64[ns](1), float64(7), int64(10), object(1)
memory usage: 139.8+ KB
None
                                date         day    aircraft  helicopter  \
count                            941  941.000000  941.000000  941.000000
mean   2023-06-09 23:59:59.999999744  472.000000  290.952179  273.433581
min              2022-02-25 00:00:00    2.000000   10.000000    7.000000
25%              2022-10-18 00:00:00  237.000000  268.000000  242.000000
50%              2023-06-10 00:00:00  472.000000  314.000000  299.000000
75%              2024-01-31 00:00:00  707.000000  332.000000  324.000000
max              2024-09-22 00:00:00  942.000000  369.000000  328.000000
std                              NaN  271.787601   66.630554   66.416490

              tank           APC  field artillery          MRL  military auto  \
count   941.000000    941.000000       941.000000   941.000000      65.000000
mean   4321.651435   8466.002125      5765.631243   642.057386    1047.507692
min      80.000000    516.000000        49.000000     4.000000     100.000000
25%    2548.000000   5219.000000      1622.000000   372.000000     600.000000
50%    3909.000000   7607.000000      3717.000000   600.000000    1178.000000
75%    6310.000000  11757.000000      9195.000000   974.000000    1437.000000
max    8768.000000  17222.000000     18333.000000  1195.000000    1701.000000
std    2367.477554   4351.443982      5158.879451   339.791399     466.162060

       fuel tank         drone  naval ship  anti-aircraft warfare  \
count  65.000000    941.000000  941.000000             941.000000
mean   69.323077   4610.648247   18.970244             424.697131
min    60.000000      0.000000    2.000000               0.000000
25%    60.000000   1276.000000   16.000000             188.000000
50%    73.000000   3263.000000   18.000000             362.000000
75%    76.000000   7100.000000   23.000000             663.000000
max    76.000000  15628.000000   28.000000             949.000000
std     7.545917   4136.943595    5.955970             281.890047

       special equipment  mobile SRBM system  vehicles and fuel tanks  \
count         922.000000           36.000000               876.000000
mean          891.031453            3.944444              9223.302511
min            10.000000            2.000000              1796.000000
25%           154.000000            4.000000              4503.000000
50%           528.500000            4.000000              6986.500000
75%          1484.250000            4.000000             12720.500000
max          3144.000000            4.000000             25023.000000
std           895.658135            0.333333              6191.688626

       cruise missiles  submarines
count       876.000000       375.0
mean       1237.265982         1.0
min          84.000000         1.0
25%         576.750000         1.0
50%        1271.000000         1.0
75%        1895.250000         1.0
max        2593.000000         1.0
std         768.385932         0.0